### ISSUE TITLE
Error: "Couldn't load tag configurable_falls:fragile as it is missing following references: minecraft: (from fabric)"

### ISSUE THREAD

**Issue by InputandOutput** [KekeCreations/Configurable-Falls#2]
Mod does not successfully load the fragile tag. Please let me know if you require additional files for troubleshooting.

**Comment by KekeCreations** [comment]
Do you still get this error if you add a block to the tag?

**Comment by InputandOutput** [comment]
I am assuming that the block tag is loaded correctly. The item tested with is BetterNether's quartz glass.
[fragile.json](https://github.com/KekeCreations/Configurable-Falls/files/15211167/fragile.json)

**Comment by KekeCreations** [comment]
What if you try minecraft:glass?

**Comment by InputandOutput** [comment]
It seems to produce the same error as mentioned in the title: "Couldn't load tag configurable_falls:fragile as it is missing following references: minecraft: (from fabric)".

**Comment by KekeCreations** [comment]
Thank you for your help/report, I will look into this!

**Comment by KekeCreations** [comment]
Hello, I have fixed this issue in V2.0.2, and that version is now out for 1.20.1 (1.20.2 coming soon). Please feel free to make a new issue post if you run into any more issues! Thank you for downloading!
